# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.220
neo_version_range=[21.1.220,)
loader_version_range=[4,)

## Rinku
rinku_version_id=3.0.1-1.21.1


## Mod Properties
mod_id=ultimate_browser
mod_name=UltimateBrowser
mod_named=Ultimate Browser
mod_license=MIT
mod_version=1.0.1
mod_group_id=nadiendev.ultimate_browser
mod_authors=NadienDev
mod_description=A fully functional Chromium web browser inside Minecraft, with multiple tabs, Picture-in-Picture mode, fullscreen browsing, a chat link interceptor, and admin commands.
tag_lanzador=NeoForge

## Metadata Website
mod_credits=NadienDev
issue_tracker=https://github.com/SrNadien/Ultimate-Browser
